### ISSUE TITLE
vendor report

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#100]
The vendor Report is still not working properly.  When I pull it it now includes language from RFP's and is not lining up columns correctly.
[vendor pull 12.5.16.xlsx](https://github.com/CityofPittsburgh/pittsburgh-purchasing-suite/files/631504/vendor.pull.12.5.16.xlsx)

**Comment by bsmithgall** [comment]
Hi Riley,

Sorry I didn't have a chance to take a look at this this weekend, but I'll look later this week.

**Comment by bsmithgall** [comment]
This should work now.
