### ISSUE TITLE
remove subscriptions from beacon

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#108]
As of 1/1/17, the city is able to do their own contracting (instead of just going through the county).  This means that we have a new bidding tool.  While we will still be double posting on Beacon for awhile, we don't want people to continue to subscribe to Beacon when they should be registering for the new bidding tool.

Can we please have Beacon take the supplies to http://pittsburghpa.gov/omb/purchasing/registration.html when they click on subscribe (either from homepage or from upper right hand corner) on beacon?

Thanks

**Comment by rileystewart** [comment]
is there any estimate of when this will get done so I can report to sam/jenn?

**Comment by bsmithgall** [comment]
I'm sort of hesitant about both this and #109 given that people are still signing up and that opportunity notifications are still going out. 

Is there a plan to notify people on the list that these things are being turned off and they shouldn't expect them anymore? Are people going to be automatically migrated to the new system, or are they going to have to re-sign up?

**Comment by bsmithgall** [comment]
At the very least, it would be good to have copy from you to put into the FAQ to clear up any confusion.

**Comment by bsmithgall** [comment]
Text for the FAQ question "How do I find out about opportunities?" also needs to be updated, as does the text for the banner at [the top of Beacon](https://procurement.pittsburghpa.gov/beacon/), which currently reads: "Find opportunities to sell to the City and sign up for emails about future ones." which will no longer be true.

**Comment by rileystewart** [comment]
Everybody that is currently signed up for Beacon has received multiple notifications from us letting them know about the new system and how to sign up (they will not be automatically added because it requires alot more information).   The problem with them still signing up is that they have no clue that they are signing up for the wrong thing.  

At this point, we will still double post opportunities on beacon so people should still get the notifications if they are signed up for a category we post on.  I just dont want the biweekly emails going out and I dont want any more people to sign up.

**Comment by bsmithgall** [comment]
Great. In that case, if you could just provide copy for the places that I mentioned above, I will finish this.

**Comment by rileystewart** [comment]
Replace the answer language in the FAQ for "how do i find out about opportunities" with "http://pittsburghpa.gov/omb/purchasing/registration.html" (just the link)

Replace the answer language for "what does the city buy" with "The short answer is — almost everything!   Go to http://pittsburghpa.gov/omb/purchasing/bid-opportunities.html to find out more"



Also remove any places they can enter their email address from the home page/FAQ page

**Comment by bsmithgall** [comment]
This is done, please take a look at the screenshots in #110. I wrote descriptive text instead of the raw links; it looked a lot more visually cohesive.
