### ISSUE TITLE
remove biweekly emails from beacon

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#109]
Can we please stop the emails that go to vendor biweekly?  I dont want them to be "spam" when we are no longer posting to beacon in the future.

Thanks

**Comment by bsmithgall** [comment]
When do you want me to do this? Combined with #108, it sounds like this is a large/substantial change that is going to remove a lot of the core functionality of Beacon. 

Are there more components of the entire suite that will be deprecated with the change or is it just Beacon? Do you need any help to migrate the existing contact information that you have to the new system?

**Comment by rileystewart** [comment]
If this could happen asap that would be great. We do not know how much of the other tools we will be changing but for now scout and conductor are still in use. We just don't want vendors signing up for a tool that we know we will be discontinuing in the future. 

Riley R. Stewart
