### ISSUE TITLE
Removing Contracts from 'in progress' in conductor

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#11]
If a contract was accidentally started in conductor, how do we remove it from the 'in progress' list and get it back to the all contracts section?

**Comment by bsmithgall** [comment]
Which contract is it?

**Comment by rileystewart** [comment]
There are about 3 right now.  This is something that I see happening either by choosing the wrong contract or in some cases we had the wrong expiration date and this contract is not up for renewal for at least another year and should be down in the all contracts section.

**Comment by rileystewart** [comment]
7096 Washing City vehicles is one for example

**Comment by bsmithgall** [comment]
A contract shows up in the "all contracts" section if and only if two conditions are met. First, the parent contract must have the "visible in conductor" flag checked. Second, the parent contract must have no children, which means that you will have to **delete all of the currently in-progress children**.
1. Go into the currently in-progress contract into the conductor admin, and get the parent ID:
   ![conductor contract detail view](https://cloud.githubusercontent.com/assets/1957344/11818554/f70dac46-a328-11e5-9257-643ef09e1255.png)
2. Delete the in-progress contract (NOTE: this will delete all work and notes associated with that contract as well):
   ![conductor contract list view](https://cloud.githubusercontent.com/assets/1957344/11818584/24640078-a329-11e5-9823-16f84af92195.png)
3. Make sure the "visible in conductor" flag is checked on the parent:
   ![scout_-_contracts_-_admin](https://cloud.githubusercontent.com/assets/1957344/11818942/21c9ee02-a32b-11e5-9969-1aa5ac9fbafb.png)

I'm also going to submit a pull request that will let you see all of the children for a given contract in the Scout admin, which should make this a bit easier:

![scout_-_contracts_-_admin](https://cloud.githubusercontent.com/assets/1957344/11819585/af5ef156-a32e-11e5-8a71-a6a9e3e24906.png)
