### ISSUE TITLE
Notes on Contract have newest at the top

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#13]
Don't know if this is a simple change, but its really annoying to have to scroll down each time to see the most recent note on a contract.  Discussed with Stephanie and Ed and would be better if it had most recent at the top, first at the bottom.

**Comment by bsmithgall** [comment]
We could re-order everything so that it's all most recent to furthest away.

**Comment by rileystewart** [comment]
YES! This would be great

**Comment by bsmithgall** [comment]
This should be fixed by f70dffb, which I've just deployed. This also adds the times to the activity log. Let me know if you see any weirdness.
