### ISSUE TITLE
Conductor not updating Scout

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#15]
Spec 7241 shows it has an updated expiration date on Conductor but not on Scout Admin.  I ran into this a few more times.  Also the vendors it shows on Conductor for this spec are spelled incorrectly but it appears correctly in Scout Admin

**Comment by bsmithgall** [comment]
For Spec 7241, are you updating the child contract (via conductor) or the parent contract (via the scout admin)? They will have two different expiration dates because they are two different contracts. The same is probably true for the vendor spellings because they are represented as different contracts.

**Comment by rileystewart** [comment]
okay this is really confusing then.  I don't want in displaying twice.  like in this example if I go to scout admin it has one contract for 7241 (even though list says 2) and it has an expiration of 12/31/15.

If I'm looking in scout and type 7241, 4 contracts pull up.  2 that expire and the end of the year and 2 with the new expiration dates.  The new expiration date should override the old one and there should still only be 2 options.  Since the contract was extended (same suppliers, same controller number, etc).

I can see us getting emails from ppl that subscribe to a contract saying its about to expire when it is already finished.

Also the information in scout admin shows me the 12/31/15 so its not even the most current so it's very confusing if I'm trying to look in admin at expired contracts

**Comment by bsmithgall** [comment]
Contracts only disappear from default search results in Scout if the "Archived" flag is marked for them. For contracts that are completed through conductor, the archived flag should be set automatically. It can be unset via the admin.

There is a bug here where contracts that should show up in the Scout admin aren't. I'll work on that and put in a patch.
