### ISSUE TITLE
expiration dates not appearing correctly on conductor

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#19]
An example of this is the Electrical Maintenance/repair (CD) contract.  This is a renewal of spec 7011. This however shows no previous spec number and no expiration date.  

The only thing with this i had to do was go in and change the current expiration date via admin scout because it was actually 3/31/16 but was showing as 2/28/16.  I changed that and suddenly all the information disappeared from conductor.

**Comment by bsmithgall** [comment]
Is this recurring or only this one? I fixed that particular one.

**Comment by rileystewart** [comment]
Electrical Maintenance & Repair also has this problem (non CD)

**Comment by bsmithgall** [comment]
Did you update that one through the Scout Admin recently? I'm trying to determine if it's a bug or if there is just something finnicky going on.

**Comment by rileystewart** [comment]
I could have. but either way I don't want it removing the information.

i.e. if I found out it was accidentally entered the wrong way and change it real quick via admin it shouldn't remove the old spec number from conductor

**Comment by bsmithgall** [comment]
I agree just trying to figure out why. I'll test a few things.

**Comment by bsmithgall** [comment]
The underlying issue will be fixed by #24, but there might be lingering issues. Let me know if you find them and I can fix them manually.
