### ISSUE TITLE
The activity stream is not showing in correct order

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#21]
For the contract Office Systems Installation and Services, etc. it appears that the activity stream is not in the proper date order.

**Comment by bsmithgall** [comment]
Is it in the right stage? It looks like it should be in the very first stage of the inquiry flow (Sent to Department) due to a flow switch on 12/15, but it appears to not have updated properly.

**Comment by rileystewart** [comment]
this was the only one I saw but since it was new change to reverse the dates I figured I'd make note of it.

**Comment by bsmithgall** [comment]
@rileystewart it looks like it didn't clear out all of the original stages. I think that if you go to the first stage and manually revert to it it should clear up.
