### ISSUE TITLE
issue completing contract in conductor

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#25]
When a contract is complete you are asked to fill in the spec/expiration/name/url
1. I edited the name to something different and continued on the process but the name did not change.
2. When you get to the step for 'Contact information', everything is required.  This should only be required if you are using a new company.  If you are renewing a contract or using a company that is already created, this should prepopulate with who the contacts are for that company and not force you to reenter and ultimately create a duplicate contact.

**Comment by rileystewart** [comment]
The best way to fix this may just be making all of these contact fields not required.

**Comment by bsmithgall** [comment]
I can make them all not required if you want.

**Comment by rileystewart** [comment]
yes! at least for the contacts part
