### ISSUE TITLE
contract not showing in conductor

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#27]
we just finished spec 7578 for decorative streetlighting from conductor.

It is now not in conductor anywhere and I am not sure why or where it has gone

**Comment by bsmithgall** [comment]
It's missing a contract type. Only County contracts, A-Bids, and B-Bids will show up in conductor. You can assign a contract type directly from the admin.

**Comment by rileystewart** [comment]
if this was done through conductor how would it be missing a contract type?  could this have happened to any other contracts?

**Comment by bsmithgall** [comment]
It's possible it was created as a new contract before the change to Conductor was made allowing different contract types.

I don't believe that it's possible, but if another one crops up open another issue and I'll look into it further.
