### ISSUE TITLE
Can't edit posting on Beacon

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#28]
Beacon does not accept emails with .us as the email address.  This is the email address from the county so any BidNet bids I try to post on Beacon will not edit (I can post because email is not required when posting through Conductor, but if I need to edit via Beacon it is required and doesn't accept this email address as valid)

**Comment by bsmithgall** [comment]
What email address exactly are you trying to put in? I am not having trouble using .us email addresses locally.

**Comment by bsmithgall** [comment]
There's a small bug that might be preventing this. I'm going to push a change which should fix it.
