### ISSUE TITLE
Date/Time Conflict on Conductor

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#31]
We are constantly having to backdate on conductor and redo dates for a contract.  The date box where you put in the time/date to mark complete is becoming increasingly difficult.  Lets say that 2 things happened on the same day. I am backdating both steps.  The first one I can probably do okay....the second one if I go back in the calendar to select the day it will automatically tell me there is a conflict (because the time is the same) and make me start all over.

It should only pop up this warning if you hit 'mark complete' and the time/date are not after the previous step.

**Comment by bsmithgall** [comment]
The way you are describing it should work is the way it works right now. You should be able to mark it complete one minute after the previous step.

**Comment by rileystewart** [comment]
The issue is that the current date/time always come up for the 'mark complete' step.

So if I am going back 5 steps....reverting.  and putting in the date of 12/1/15 2:00pm for that step.  If I then want to show the next step happened the same day, I go back on the calendar to 12/1/15 and when I select it, it automatically says the time/date conflict because the current time is 12:30 and it takes the current time.  I should be able to set the date and then manually change the time. 

so if this situation was happening and I was trying to set the next step to 12/1/15 at 4pm, I would have to go and select the date 12/2/15 from the calendar, then change the time to 4pm, then go back and select 12/1/15 which is 3 steps for trying to set one time.

**Comment by bsmithgall** [comment]
Maybe the easiest way to do this would be to not have it auto-populate with anything in that section so that you would have to fill it out yourself before you could mark things as complete?

**Comment by bsmithgall** [comment]
Let me know if this is an acceptable fix. I can't think of another good way to do it.

**Comment by bsmithgall** [comment]
@rileystewart can you let me know if this is OK? I'll work on it with #33 and #32

**Comment by bsmithgall** [comment]
Instead, I made the date pre-populate with the stage enter time, which should hopefully resolve this issue.
