### ISSUE TITLE
ability to remove certain contracts from metrics

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#32]
I'm not sure if I put in a github issue for this or not.  We have some bad data in the metrics section...either because we uploaded incorrect numbers initially or because Stephanie/ed didn't understand how and when to mark status's complete.  This means we have some numbers that are DRASTICALLY incorrect.  I would like the ability to remove some of these from metrics either by having the ability to edit timelines of completed contracts or selecting to remove them in some other way.

Going forward I don't see this as being a huge problem so a 3rd way would be I send you a list of which ocntracts to remove and we do it as a one time thing

**Comment by bsmithgall** [comment]
I could add a flag where you could control individual contracts in the admin.

**Comment by rileystewart** [comment]
this would be amazing! for these ones I want them to be included in the
future but I want this to be flow specific.
