### ISSUE TITLE
Conductor Download Question

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#38]
Why in the download of all contracts are there contracts that show 'not started' status but that they are in the renewal flow?

Also I am not seeing some that show up under the 'completed' status in conductor (i.e. Air Filters).  Once a contract is completed, I would think it would go back to 'not started' status with a new expiration date.  Air filters is not in conductor at all

**Comment by bsmithgall** [comment]
It looks like things are being misclassified in the status section. I'll look into it.
