### ISSUE TITLE
This date creates conflict

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#42]
While changing it to the day the last step was completed helped fix some of the issues, there are still issues with marking things complete

a great example of this is the furnish/install pvc swimming pool liners contract 7020

The bid closed at 1/27/16 2:09pm
Bid tab was received today.  Stephanie is trying to mark this step complete but it is impossible to mark it complete with a 1/28 date.  Because the time is 2:09 of last step and the current time is 10:45am.  

The validation to check if the date conflicts should not happen until the agent physically hits the 'mark complete' button.

**Comment by bsmithgall** [comment]
Ok I'll take a look at this.

**Comment by bsmithgall** [comment]
In the meantime, if you change the time before you change the date that should work.

**Comment by rileystewart** [comment]
that won't work in this example.  Because the system will not let you
change the time to something that happened before the previous step.  ie
930am is before the 2:30pm time that the previous step was completed, so
the system will error

**Comment by bsmithgall** [comment]
Ah ok. I'm going to submit a patch which will still warn you if the time you have selected is in the future but let you change the date. Actual validation will still occur on the backend to prevent saving incorrect data.
