### ISSUE TITLE
editing the name of a contract type deletes all contracts

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#44]
I changed the name of pboe to Pittsburgh Board of Education and URA to Urban Redevelopment Authority.  Both of these then had all contracts deleted from scout.  we had 3 PBOE contracts and 1 valid URA contract

**Comment by bsmithgall** [comment]
Looks like it's fine now, though there's only 2 PBOE contracts. Do you remember which one is missing? There's a few contracts that don't have a contract type but do have a controller number, so it could be one of them:
- TECHNOLOGY BIDDING & PURCHASING PROGRAM
- Aftermarket Parts
- 6931 - PRE-QUALIFIED CONTRACT FOR FORMS PRINTING SERVICES [ARCHIVED]
- FURNISH: DECORATIVE STREETLIGHTING POLES AND LED FIXTURES FOR HIGHLAND AVENUE LINERS
