### ISSUE TITLE
take away tags from beacon

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#50]
I don't want the suppliers or public to see what categories we are tagging the opportunities with.  sometimes we are over tagging with items that may or may not be covered in the RFP.  We don't want those tags displaying unless you are a city worker logged in (or if that's too hard just take away display from all users...I can always see when I edit the opportunity)

**Comment by rileystewart** [comment]
still seeing tags when I went to beacon, clicked on an opportunity, and wasn't logged in as admin

**Comment by bsmithgall** [comment]
Change is merged into master, but the next deploy will also involve the much larger change involving the new logins with passwords. Therefore, I want to do a rollout over a weekend with an email to all users, or whatever rollout plan you think is appropriate.
