### ISSUE TITLE
contracts not showing on scout

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#53]
Stephanie finished a contract on conductor (7560) for flag supplies.  It shows in admin but doesn't show when you search in scout

**Comment by bsmithgall** [comment]
This one? https://procurement.pittsburghpa.gov/scout/contracts/2653

**Comment by rileystewart** [comment]
ya. it wasn't showing for at least 10 minutes after it was entered.  Is this normal to have that kind of a time lapse with entry?  It isn't something I have noticed in the past when I enter new contracts

**Comment by bsmithgall** [comment]
It can. The search isn't automatic, and should refresh when any of the
underlying data is changed. This refresh can take some time.
