### ISSUE TITLE
spec disappears from contract

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#54]
This has happened before and I don't know why.  Contract for construction material is in progress and now says 'item #4007' when it should say spec 7449

**Comment by bsmithgall** [comment]
You should be able to add the spec number directly from the Admin: https://procurement.pittsburghpa.gov/admin/conductor-contract/edit/?id=4007 It looks like this contract was started as a new contract, so if you need it to be linked to another contract (as a child contract), I'll need the item # for the old one.
