### ISSUE TITLE
contracts not appearing in conductor

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#55]
I pulled a report and am seeing that 2 current contracts (spec 7341-Repair:heavy equipment ii and Printing and Embossing Business Cards-A-072-15) are not showing.  I looked in admin Scout and they display correctly there w/ the conductor box checked. I'm not sure if there are any other contracts w/ similar situations.  I want every county/abid showing in conductor unless it has been manually from conductor.

**Comment by bsmithgall** [comment]
Where aren't they appearing?

**Comment by rileystewart** [comment]
in conductor

**Comment by bsmithgall** [comment]
Like in the interface? In a download? You said you pulled a report, but I need a bit more detail to look at this. I'll try to get to it tonight.

**Comment by rileystewart** [comment]
I pulled a report of all contracts from metrics:download all.  I noticed that 2 current contracts that were in that list (after I filtered out the archived and not in conductor contracts) were actually NOT displaying under inprogress or all contracts in conductor.  I went to Scout admin to see if the box there was unchecked and both of these contracts are set to display in conductor.

**Comment by rileystewart** [comment]
I actually found a lot of different contracts that aren't displaying in conductor.  For some reason some iteration of the contract is listed in that download all contracts as archived.  We have archived no contracts....only removed from conductor.  This is really worrisome because some of these contracts we didn't see and now we are late to start them!  I don't know how something gets in an 'archived' status but it should never be archived...just expired or removed from conductor!  Here is a list of ones I noticed that need to be in conductor but aren't.  As for the archive issue right now there are 101 contracts in archived status that could be messing us up.

Disposable Medical Supplies-7387
Elemental Chlorine-i3190
E-Waste Recycling-6760
Printing & Embossing Business Cards-A-072-15
Rental of Equipment for Storm Sewer Systems-7207
Repair: Heavy Equipment II-7341
Sign Blanks-7552
Tasers, Taser Kits-7068
[Contracts.xlsx](https://github.com/CityofPittsburgh/pittsburgh-purchasing-suite/files/157617/Contracts.xlsx)

I've also attached what I'm looking at and added a column for the ones I immediately know are labeled archived when they should be just removed from conductor

**Comment by bsmithgall** [comment]
Looking really quickly it seems like a lot of the contracts that you've pointed out have children that were archived in conductor. For example, if you look at the Scout Admin page for the first one (Disposable Medical Supples: https://procurement.pittsburghpa.gov/admin/contract/edit/?id=2274), you can see under "children" it has a child with item # 3978, which is listed as archived (here's the Conductor contract admin page for it: https://procurement.pittsburghpa.gov/admin/conductor-contract/edit/?id=3978).

This would explain why these contracts aren't showing up in Conductor: only the _furthest descendent contract_ is displayed. This means that if you have a parent contract (like the disposable medical supplies contract you mentioned), it won't display that contract, only its children. This is to prevent every contract ever from being displayed in Conductor. Additionally, _archived_ contracts aren't displayed in conductor, you have to undo them from the Admin. Therefore, if you _archive_ a child contract, it will disappear. These children are all marked as archived, so they don't appear, and neither do their parents.

However, finding and unarchiving these children is doable. I'm going to use the e-waste recycling contract as an example here:
1. Get the item # for the contract you are interested in (they should be available on the spreadsheet)
2. Go to the Scout contract admin page for that contract. The easiest way is the just change the URL: 
   `https://procurement.pittsburghpa.gov/admin/contract/edit/?id=PUT THE ITEM NUMBER HERE`
3. Check to see if the contract has archived children:
   <img width="1279" alt="scout_-_contracts_-_admin" src="https://cloud.githubusercontent.com/assets/1957344/13507917/e748a050-e152-11e5-9754-1116bb01c7c4.png">
4. Go to the conductor contract admin page for the child. Again the easiest way is just to change the URL: `https://procurement.pittsburghpa.gov/admin/conductor-contract/edit/?id=PUT THE CHILD ITEM NUMBER HERE`. In this case, the item number for the child contract is 2607. We can see that from the above screenshot.
5. Uncheck the "archive" box. You'll probably also want to update the description to remove the " [Archived]" from the end.
   <img width="1279" alt="conductor_-_contracts_-_admin" src="https://cloud.githubusercontent.com/assets/1957344/13508034/5b8551e8-e153-11e5-93d0-a0fda9746ea7.png">

**Comment by rileystewart** [comment]
Okay well ultimately I want to remove this whole archived contract option completely and only have removed from conductor. Removing from conductor. All current contracts in archived status should go go removed from conductor status and uncheck the box from the contract in scout. Then if I want to manually add it back to conductor I would go into admin:scout:contracts, search the contract, and check the box

Riley R. Stewart

**Comment by rileystewart** [comment]
Also doing the way you suggested doesn't work because it just put "e-waste" back into the in progress section. This contrAct needs to be under all contracts because it has not been started as with the rest of them.

Riley R. Stewart

**Comment by bsmithgall** [comment]
In that case, you can delete the child and make sure the parent contract is not archived and visible in conductor
<img width="1279" alt="conductor_-_contracts_-_admin" src="https://cloud.githubusercontent.com/assets/1957344/13508596/b5b4f66c-e155-11e5-962c-e275d868a5c6.png">

Before doing that, I would make sure that you are deleting the proper thing, as it isn't a recoverable action.

**Comment by rileystewart** [comment]
still can't get heavy equipment:II to show in conductor.

**Comment by bsmithgall** [comment]
I'll look at that one this weekend. Can you give me an item number to look at ?

**Comment by rileystewart** [comment]
spec 7341/controller 51048

**Comment by bsmithgall** [comment]
That one is the parent contract to a contract with spec number 7213, which is currently in progress. If that is incorrect, I can unlink them.

**Comment by bsmithgall** [comment]
(see: https://procurement.pittsburghpa.gov/conductor/contract/3964/stage/2510)
