### ISSUE TITLE
the boxes in admin don't display/mean anything

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#56]
I've noticed this tons.  In Admin (for Scout, Conductor, Beacon, etc) the 'check boxes' don't mean anything.  For example under Admin>Scout>Contract Types there are boxes under opportunities and managed by Conductor on this page.  PWSA and Pittsburgh water and sewer authority both have boxes appearing in each column.  Pittsburgh water and sewer authority if you click into it though shows it allows opportunities but is not managed by conductor.  PWSA has both boxes showing but if you click in neither one is checked

**Comment by rileystewart** [comment]
same thing if you are in admin>conductor>contracts.  the 'Archived' column has no check marks if one is archived

**Comment by bsmithgall** [comment]
They do mean things.

In contract types `Allow Opportunities` adds that particular type to the dropdown of available contract types for Beacon. `Managed by Conductor` makes that all contracts type of contract appear in the `All contracts` section. That's how A-Bid, B-Bid and County contracts all show up in Conductor.

**Comment by rileystewart** [comment]
This is now fixed.  It used to be displaying boxes with no rhyme or reason.  Now it is displaying check marks and dashes.  This was not the way it was before.

**Comment by bsmithgall** [comment]
Oh I bet the images weren't rendering properly, but that should be fixed.
