### ISSUE TITLE
issues 'finishing' contract in conductor

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#58]
This is a 2 part issue.  After ed/Stephanie check the box sent to city controller the step becomes 'City Contract Complete'.  The next time they hit 'update' it immediately takes them to the box to fill out the contract information with no option of putting in the date.  In most cases, we are not updating it the exact day that we received the information from the controller.  If for example Stephanie went on vacation and came back to an email that the contract was extended, she would want to put the day the email came back as the 'city contract complete date' but this is not an option.

While looking at this issue, I've noticed that there is also an issue with blank contacts being added.  If for example I am renewing a contract w/ 2 existing contractors I choose 'choose existing company' and enter the controller number.  On the next page it asks for contact information which I would leave blank because they're already in there.....when I go to Admin>Scout>Companies though and select that company....it has a blank contact that was added.  Contacts should only be added if there is information in it.

**Comment by bsmithgall** [comment]
Blank contacts can be deleted and/or removed from the contracts section. I'll look into new ones being generated. 

As for the other issue, you can adjust the time by clicking this in the fillout:
<img width="1279" alt="banners_and_alerts_and_pittsburgh_purchasing_suite" src="https://cloud.githubusercontent.com/assets/1957344/13533394/454e1684-e1fe-11e5-9989-cd6d6ecd07e1.png">

I originally added this when Stephanie asked for it.
