### ISSUE TITLE
Contract will not leave conductor

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#59]
We have 'finished' and completed the contract for Traffic Sign posts (7206) 3x through conductor and yet it doesn't leave in progress. I watched Ed complete each step 2x.  Each time it adds a new contract into Scout but still stays in progress in conductor.  The City contract complete date should be 1/14

**Comment by bsmithgall** [comment]
I don't see it in progress.
