### ISSUE TITLE
Metrics detail isn't showing

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#60]
When I go into Metrics and choose formal bidding, I am looking at the bar chart....I try to click on the bar to see more data and it doesn't appear.

**Comment by bsmithgall** [comment]
Looks like Chrome deprecated a piece of the SVG API: https://www.chromestatus.com/feature/5708851034718208 

If you are using Chrome, it would probably work on a different browser in the short-term, but I'll add a polyfill dependency and I'll try to get this patched. 

I'm going to try to figure out if I can deploy a fix for this and for the Beacon thing (#50) without patching the users with passwords, but it might have to wait until after the larger change is released. I never got approval for the release plan that I sent a few weeks ago, so I'm just sort of waiting.

**Comment by bsmithgall** [comment]
This is fixed and I've reworked the history to allow for more fixes while we wait for the password switchover approval.
