### ISSUE TITLE
conductor steps not recording correctly

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#66]
I just went over to Ed's desk to watch what he was doing.

He needed to backdate a contract for Rental for Special Events.  He had to start from the beginning.  He started at 5/15/15.  For the 'Department review returned' step he had the date/time 6/30 8:00pm in and hit 'mark complete'.  Not only did it record the steps time as 7/1 12:00am, but it also marked the next step complete as well.

I saw this happen on 2 different contracts.

**Comment by bsmithgall** [comment]
Can I get item numbers for these?
