### ISSUE TITLE
calendar not working in conductor

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#67]
Furnish/install Pvc Swimming Pool Liners

Trying to mark city contract complete for 3/25 and the calendar is all grayed out.

**Comment by bsmithgall** [comment]
Fixed. This would be fixed by the proposed change in #65 -- if you could take a look at the comments either there or in #64 I will merge it.

**Comment by rileystewart** [comment]
What do you need for me to confirm this fix

Riley R. Stewart

**Comment by bsmithgall** [comment]
The message describing the change is in number 64, but I've copied the relevant part below:

---

When these steps occur in sequence, a gap of five days appears between step one and step two. This commit will automatically mark the step two enter date to be equal to the step one exit date.

---

So basically in our scenario, the step that you just completed will have it's enter date checked against the _previous_ step's exit date. In the event that they don't match, it will automatically make them match by taking the start date and moving it backwards to match the previous date's exit date.

**Comment by rileystewart** [comment]
Yes. The exit time of the previous step is always the start time of the next step.  The entry time of the current step is the completed time of the previous step.

Riley R. Stewart

**Comment by bsmithgall** [comment]
Great, I'll merge and try to get a deploy out tonight.
