### ISSUE TITLE
Conductor Metrics is not working correctly

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#69]
I am looking at the Metrics page for Formal Bidding.  The "Count of contracts by days spent in given step" does not appear to be correct.  right now it shows 21 contracts in 'Department Review Sent' status, but there is only 1.  The Department Review Returned bar is also incorrect.

**Comment by bsmithgall** [comment]
This looks busted, I will take a look later.
