### ISSUE TITLE
Admin>Scout>Contracts Edit not working

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#72]
If you go to the admin menu and click on Scout>contracts, a list of all the contracts we have appears.  From this screen, specific fields are blue and clickable (description, controller #, and expiration).  These are able to be edited without specifically clicking into the individual contract.  The 'Expiration' field however is not working correctly.  If I click in to change the expiration date (which is common because lots extend 1 year), the year field is blank and the last valid year that appears is 2015.

**Comment by rileystewart** [comment]
This is still not working. There is no real easy way for me to attach screenshots except making a Microsoft word document and attaching.
[github_admin_date.docx](https://github.com/CityofPittsburgh/pittsburgh-purchasing-suite/files/268025/github_admin_date.docx)

**Comment by bsmithgall** [comment]
Sorry, missed a line in some reconciliation. Patch incoming.
