### ISSUE TITLE
Scout>Admin>Contracts

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#74]
When you click in to edit a contracts information in Admin, the details are not displaying correctly.  I was trying to add myself as a follower of a contract and make it not visible in conductor.   When in the editing screen, the Children, Companies, and Followers fields are all messed up (use controller number 45753, MRO Supplies to see what I am talking about since I can't seen to paste a screen shot).

**Comment by bsmithgall** [comment]
Issue with static assets after deploy. Should be fixed.
