### ISSUE TITLE
can't modify start time in conductor

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#77]
I'm trying to change the start date of the 'Washing of city Vehicles' contract in conductor.  It will not let me change it to May.  When I hit modify start contract time, it is all greyed out.

**Comment by bsmithgall** [comment]
I'm not exactly sure what you are trying to do. Could you please give me:
1. A spec number for this contract?
2. Which start time you are trying to modify (as in, do you mean the start time of the first step of the contract? the step the contract is currently on?)

If you could provide a screenshot that would be immensely valuable.

**Comment by bsmithgall** [comment]
Is this is still a problem?

**Comment by rileystewart** [comment]
Errors and Omissions is doing it now.  We try change the start date to today and it won't let us change it to any date after when the original start time was set
[github_change_start.docx](https://github.com/CityofPittsburgh/pittsburgh-purchasing-suite/files/269085/github_change_start.docx)

**Comment by rileystewart** [comment]
This is happening again in one I just created (cleaning of training academy ii).  I initially put 6/8/16 when creating it but it actually wasn't started until some day like 6/15.  If you hit modify start time you can only start it earlier in time but not later.
