### ISSUE TITLE
contract not displaying in conductor

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#79]
Spec 7341 is not displaying in conductor.  I can't figure out why or how to get it to display even though the boxes are checked correctly.

In Scout Admin it is marked as visible in conductor.

**Comment by bsmithgall** [comment]
This contract has a child contract ([Item #3963](https://procurement.pittsburghpa.gov/admin/contract/edit/?id=3963)), which has a different Spec Number (7213). For what it's worth, that contract _also_ has a child contract ([Item #3964](https://procurement.pittsburghpa.gov/admin/contract/edit/?id=3964)) which has _another_ different spec number (7214). If this is an error and the original contract with spec 7341 (Item #2257) should be visible in conductor let me know and I can break the link between that and Item #3963, and it should show up in the "all contracts" section.

**Comment by rileystewart** [comment]
ya. this whole child/parent thing is very weird because each time we renew a contract it creates a completely new contract in scout.  I would rather not have parent/child relationships impact whether something shows in conductor or not....If a contract is made 'not visible' only that contract should be made not visible.  If a contract goes through all the steps and a new one is put in place, that old one should be come not visible and the new one should be made visible.

**Comment by bsmithgall** [comment]
This has been updated:

<img width="1243" alt="screen shot 2016-06-22 at 7 12 27 pm" src="https://cloud.githubusercontent.com/assets/1957344/16286894/557e39d4-38ad-11e6-8a99-d64eff681936.png">

I will look into that suggestion, but right now the parent/child is the primary way everything stays properly linked together.

**Comment by rileystewart** [comment]
I guess I just don't understand why we need a parent/child relationship as it seems to do nothing.  I don't need to know what the previous contract that was in place was.  Each renewal is part of that specific contract and if we choose new contract, it is a new entry in Scout.
