### ISSUE TITLE
two contracts not showing up in conductor

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#84]
specs 7396 and spec 7552 are not showing up in conductor.

If this is once again tied to the parent/child thing then I think we need to unlink them.  This seems to be causing more issues than it is helping.

**Comment by bsmithgall** [comment]
A lot of the underlying architecture of conductor is based on parent/child relationships. It would not be super straightforward to unlink everything.

**Comment by bsmithgall** [comment]
Neither of these are because of parent/child relationships.
- Spec 7552 was archived: https://procurement.pittsburghpa.gov/admin/contract/edit/?id=4131. Unarchive the contract (and fix the description) and it will re-appear.
- Spec 7396 became spec 7457 between item number 3934 and item number 4631. If those are two different contracts/specs, you should just create a new contract in Scout.

**Comment by rileystewart** [comment]
okay well if something is archived it should show that in Admin>Scout>Contracts.  Having the list under Admin>Conductor>Contracts be different is extremely confusing.

Also this whole archiving thing should only be if I check a box to a contract in Admin>Scout>Contracts.  Everything that is 'removed' from conductor should be 'removed from conductor' status, not archived.

**Comment by rileystewart** [comment]
Also with the sign blank one as an example, I need it to appear back under all contracts and not 'in progress', so simply unchecking archived doesn't fix the problem with this contract.

**Comment by bsmithgall** [comment]
In that case, you should just delete the formerly archived contract (item number 4131), and it's parent will show up in its place. I can submit a patch that will make archived contracts appear in the scout admin list.

**Comment by rileystewart** [comment]
I'm just saying that archived right now is two different things(one for conductor and one for scout)

I would prefer anything removed from conductor, whether it is in progress or in the all contracts when removed to result in "removed from conductor" status.  It would then disappear from the admin>conductor>contracts list but still be in the admin>scout>contracts list with the "visible in conductor" box unchecked.  If someone picked "remove from conductor and scout" the same would happen except it would also check the archived box in admin>scout>contracts.

I understand that this means that when someone selects remove from conductor that wherever the contract was in progress will be removed but I am okay with that.

Riley R. Stewart

**Comment by bsmithgall** [comment]
Ok, I think the patch I am proposing will do basically that.

**Comment by rileystewart** [comment]
Okay. As long as the only way to archive something is from unchecking the box in admin>scout>contracts or Ed/Stephanie selecting "remove from both conductor and scout".

This should also cleanup the statuses of the excel sheet download all I was talking about

Riley R. Stewart

**Comment by bsmithgall** [comment]
I've submitted the patch and it will be available as soon as I deploy. The logic for archiving hasn't changed, but what shows up in the Scout admin has. I've made it easier to move things back into the Conductor queue if they were inadvertently archived, along with making them show up in search results.

A few notes:
- **Active, in-progress conductor contracts** will only show up in the Conductor admin. Inactive Conductor and non-Conductor contracts will show up in the Scout admin.
- The "Visible in Conductor" flag only applies to _non-in-progress_ Conductor contracts. Internally, we use this flag to keep track of if a contract is "complete" or still in progress. **Please do not change this flag for contracts that are currently in-progress.** I have changed the display on the admin page to make this change a bit more apparent.

An example gif of the workflow is here:

![funfun](https://cloud.githubusercontent.com/assets/1957344/16603112/a07d19f2-42e7-11e6-9d3f-34c29ed06f5d.gif)
