### ISSUE TITLE
can't find contract

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#87]
I can't find the contract for 7396 PARTS: HEAVY EQUIPMENT, LANDSCAPING EQUIPMENT, SMALL EQUIPMENT, ETC. in conductor.

**Comment by bsmithgall** [comment]
It was replaced by a contract with the same description and spec number 7457. You can see where that happened [in the admin](https://procurement.pittsburghpa.gov/admin/contract/edit/?id=4631).

**Comment by bsmithgall** [comment]
[Here's that contract in scout](https://procurement.pittsburghpa.gov/scout/contracts/4642).
