### ISSUE TITLE
Unable to backdate properly

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#88]
Contract 7032 "Rental of Portable Classrooms", we change the start date to 8/15 and it still says that it took 14 days to get the department review sent. Can't get the start date to be 8/15 and the day the department review sent to be 8/15 and for it to say 'Took 0 days to finish'

**Comment by bsmithgall** [comment]
Hi Riley, I don't see this contract in conductor. I only see "Rental of Portable Classroom Trailer - Fire" -- could you provide a link?

**Comment by rileystewart** [comment]
That is the one I am referring to

Riley R. Stewart
